[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -D DEVICE_KIND=\"tag\"
  -D TAG_DEVICE_ID=\"tag-001\"
  -D TAG_EMPLOYEE_ID=\"employee-1\"
  -D BLE_SERVICE_UUID=\"8f240001-6f8d-4f13-a42a-8434f84f0001\"
  -D BLE_STATUS_CHAR_UUID=\"8f240002-6f8d-4f13-a42a-8434f84f0001\"
  -D BLE_PROVISION_CHAR_UUID=\"8f240003-6f8d-4f13-a42a-8434f84f0001\"
